// src/data.js

export const students = [
  { id: "S001", name: "Avery Kim", gpa: 3.2, major: "Physics" },
  { id: "S002", name: "Jordan Lee", gpa: 2.8, major: "Chemistry" },
  { id: "S003", name: "Riya Patel", gpa: 3.6, major: "Biology" },
  { id: "S004", name: "Diego Rivera", gpa: 3.0, major: "Math" },
  { id: "S005", name: "Noah Williams", gpa: 2.9, major: "CS" },
];

export const courses = [
  { id: "PHY101", title: "Physics I", level: 100 },
  { id: "PHY201", title: "Physics II", level: 200 },
  { id: "PHY301", title: "Modern Physics", level: 300 },
  { id: "PHY350", title: "Quantum Mechanics I", level: 300 },
  { id: "MTH101", title: "Calculus I", level: 100 },
  { id: "MTH201", title: "Calculus II", level: 200 },
  { id: "MTH310", title: "Linear Algebra", level: 300 },
  { id: "MTH320", title: "Probability", level: 300 },
  { id: "BIO120", title: "Intro Biology", level: 100 },
  { id: "BIO210", title: "Genetics", level: 200 },
  { id: "BIO320", title: "Molecular Biology", level: 300 },
  { id: "CHE101", title: "Gen Chemistry", level: 100 },
  { id: "CHE210", title: "Organic Chemistry", level: 200 },
  { id: "CHE330", title: "Physical Chemistry", level: 300 },
  { id: "CS110", title: "Intro to CS", level: 100 },
  { id: "CS210", title: "Data Structures", level: 200 },
  { id: "CS310", title: "Algorithms", level: 300 },
  { id: "CS320", title: "Computer Architecture", level: 300 },
  { id: "CS330", title: "Databases", level: 300 },
  { id: "INT400", title: "Computational Biology", level: 400 },
];

export const concepts = [
  { id: "K_VEC", name: "Vectors" },
  { id: "K_DER", name: "Derivatives" },
  { id: "K_INT", name: "Integrals" },
  { id: "K_SER", name: "Series" },
  { id: "K_DIFF", name: "Diff Eq" },
  { id: "K_KIN", name: "Kinematics" },
  { id: "K_EM", name: "E&M" },
  { id: "K_REL", name: "Relativity" },
  { id: "K_QM", name: "Quantum Basics" },
  { id: "K_BIO", name: "Cell Structure" },
  { id: "K_GEN", name: "Mendelian" },
  { id: "K_DNA", name: "DNA Rep" },
  { id: "K_PROT", name: "Protein Synthesis" },
  { id: "K_CHE", name: "Stoichiometry" },
  { id: "K_ORG", name: "Functional" },
  { id: "K_THERM", name: "Thermo" },
  { id: "K_CS1", name: "Loops" },
  { id: "K_CS2", name: "Arrays" },
  { id: "K_CS3", name: "LinkedList" },
  { id: "K_CS4", name: "Recursion" },
  { id: "K_ALG", name: "Complexity" },
  { id: "K_ARCH", name: "Pipelines" },
  { id: "K_DB", name: "Normalization" },
  { id: "K_STATS", name: "Random Var" },
  { id: "K_LINALG", name: "Matrix Ops" },
  { id: "K_BIOINF", name: "Seq Alignment" },
];

export const courseConcepts = [
  // Physics I & II
  { course_id: "PHY101", concept_id: "K_VEC" },
  { course_id: "PHY101", concept_id: "K_KIN" },
  { course_id: "PHY201", concept_id: "K_VEC" },
  { course_id: "PHY201", concept_id: "K_EM" },
  { course_id: "PHY301", concept_id: "K_REL" },
  { course_id: "PHY301", concept_id: "K_EM" },
  { course_id: "PHY350", concept_id: "K_QM" },
  { course_id: "PHY350", concept_id: "K_REL" },
  // Calculus I & II
  { course_id: "MTH101", concept_id: "K_DER" },
  { course_id: "MTH101", concept_id: "K_INT" },
  { course_id: "MTH201", concept_id: "K_SER" },
  { course_id: "MTH201", concept_id: "K_DIFF" },
  { course_id: "MTH310", concept_id: "K_LINALG" },
  { course_id: "MTH310", concept_id: "K_VEC" },
  { course_id: "MTH320", concept_id: "K_STATS" },
  { course_id: "MTH320", concept_id: "K_DIFF" },
  // Biology
  { course_id: "BIO120", concept_id: "K_BIO" },
  { course_id: "BIO210", concept_id: "K_GEN" },
  { course_id: "BIO210", concept_id: "K_DNA" },
  { course_id: "BIO320", concept_id: "K_PROT" },
  { course_id: "BIO320", concept_id: "K_DNA" },
  // Chemistry
  { course_id: "CHE101", concept_id: "K_CHE" },
  { course_id: "CHE210", concept_id: "K_ORG" },
  { course_id: "CHE330", concept_id: "K_THERM" },
  { course_id: "CHE330", concept_id: "K_DIFF" },
  // CS
  { course_id: "CS110", concept_id: "K_CS1" },
  { course_id: "CS110", concept_id: "K_CS2" },
  { course_id: "CS210", concept_id: "K_CS2" },
  { course_id: "CS210", concept_id: "K_CS3" },
  { course_id: "CS210", concept_id: "K_CS4" },
  { course_id: "CS310", concept_id: "K_ALG" },
  { course_id: "CS310", concept_id: "K_CS4" },
  { course_id: "CS320", concept_id: "K_ARCH" },
  { course_id: "CS320", concept_id: "K_CS3" },
  { course_id: "CS330", concept_id: "K_DB" },
  { course_id: "CS330", concept_id: "K_CS2" },
  // Interdisciplinary
  { course_id: "INT400", concept_id: "K_BIOINF" },
  { course_id: "INT400", concept_id: "K_PROT" },
  { course_id: "INT400", concept_id: "K_LINALG" },
];

export const enrollments = [
  { student_id: "S001", course_id: "PHY101", term: "FALL25", grade_num: 2.7 },
  { student_id: "S001", course_id: "MTH101", term: "FALL25", grade_num: 2.3 },
  { student_id: "S001", course_id: "CS110", term: "FALL25", grade_num: 3.0 },
  { student_id: "S001", course_id: "MTH310", term: "FALL25", grade_num: 2.9 },
  { student_id: "S001", course_id: "CS310", term: "FALL25", grade_num: 3.1 },
  { student_id: "S002", course_id: "CHE101", term: "FALL25", grade_num: 2.5 },
  { student_id: "S002", course_id: "MTH101", term: "FALL25", grade_num: 2.6 },
  { student_id: "S002", course_id: "PHY201", term: "FALL25", grade_num: 2.8 },
  { student_id: "S002", course_id: "CHE330", term: "FALL25", grade_num: 2.4 },
  { student_id: "S003", course_id: "BIO120", term: "FALL25", grade_num: 3.7 },
  { student_id: "S003", course_id: "MTH101", term: "FALL25", grade_num: 3.1 },
  { student_id: "S003", course_id: "BIO210", term: "FALL25", grade_num: 3.2 },
  { student_id: "S003", course_id: "BIO320", term: "FALL25", grade_num: 3.3 },
  { student_id: "S004", course_id: "PHY101", term: "FALL25", grade_num: 3.0 },
  { student_id: "S004", course_id: "CS110", term: "FALL25", grade_num: 3.1 },
  { student_id: "S004", course_id: "CS210", term: "FALL25", grade_num: 2.9 },
  { student_id: "S004", course_id: "CS320", term: "FALL25", grade_num: 2.8 },
  { student_id: "S005", course_id: "CS110", term: "FALL25", grade_num: 2.4 },
  { student_id: "S005", course_id: "CHE101", term: "FALL25", grade_num: 2.7 },
  { student_id: "S005", course_id: "CHE210", term: "FALL25", grade_num: 2.5 },
  { student_id: "S005", course_id: "CS330", term: "FALL25", grade_num: 2.6 },
];

export const weaknesses = [
  { student_id: "S001", concept_id: "K_VEC", mastery: 0.35 },
  { student_id: "S001", concept_id: "K_DER", mastery: 0.42 },
  { student_id: "S001", concept_id: "K_KIN", mastery: 0.55 },
  { student_id: "S001", concept_id: "K_CS2", mastery: 0.52 },
  { student_id: "S001", concept_id: "K_LINALG", mastery: 0.40 },
  { student_id: "S001", concept_id: "K_ALG", mastery: 0.38 },
  { student_id: "S002", concept_id: "K_CHE", mastery: 0.38 },
  { student_id: "S002", concept_id: "K_INT", mastery: 0.43 },
  { student_id: "S002", concept_id: "K_EM", mastery: 0.40 },
  { student_id: "S002", concept_id: "K_THERM", mastery: 0.36 },
  { student_id: "S003", concept_id: "K_BIO", mastery: 0.50 },
  { student_id: "S003", concept_id: "K_GEN", mastery: 0.46 },
  { student_id: "S003", concept_id: "K_DNA", mastery: 0.41 },
  { student_id: "S003", concept_id: "K_PROT", mastery: 0.44 },
  { student_id: "S004", concept_id: "K_VEC", mastery: 0.49 },
  { student_id: "S004", concept_id: "K_CS2", mastery: 0.44 },
  { student_id: "S004", concept_id: "K_CS3", mastery: 0.39 },
  { student_id: "S004", concept_id: "K_ARCH", mastery: 0.37 },
  { student_id: "S005", concept_id: "K_CS1", mastery: 0.40 },
  { student_id: "S005", concept_id: "K_CHE", mastery: 0.41 },
  { student_id: "S005", concept_id: "K_ORG", mastery: 0.37 },
  { student_id: "S005", concept_id: "K_DB", mastery: 0.39 },
];

export const availability = [
  { student_id: "S001", day: "Mon", hour_start: 15, hour_end: 17 },
  { student_id: "S001", day: "Tue", hour_start: 19, hour_end: 20 },
  { student_id: "S002", day: "Mon", hour_start: 16, hour_end: 18 },
  { student_id: "S003", day: "Mon", hour_start: 14, hour_end: 16 },
  { student_id: "S004", day: "Mon", hour_start: 10, hour_end: 12 },
  { student_id: "S005", day: "Mon", hour_start: 13, hour_end: 15 },
];

export const resources = [
  // Added fields: difficulty (1=beginner,5=advanced), rating (1-5 user quality), tags (quick filtering: 'foundations','practice','deep-dive','visual')
  { id: "R001", type: "video", url: "https://www.khanacademy.org/math/linear-algebra/vectors-and-spaces", concept_id: "K_VEC", duration: 12, difficulty: 2, rating: 4.6, tags: ["foundations","visual"] },
  { id: "R002", type: "quiz", url: "https://www.proprofs.com/quiz-school/", concept_id: "K_VEC", duration: 8, difficulty: 2, rating: 4.1, tags: ["practice"] },
  { id: "R003", type: "video", url: "https://www.khanacademy.org/math/calculus-1/derivative-intro", concept_id: "K_DER", duration: 15, difficulty: 2, rating: 4.7, tags: ["foundations","visual"] },
  { id: "R004", type: "notes", url: "https://www.paulstruckmath.com/derivatives-cheatsheet", concept_id: "K_DER", duration: 7, difficulty: 1, rating: 4.3, tags: ["summary","quick"] },
  { id: "R005", type: "video", url: "https://www.khanacademy.org/math/calculus-1/integration-calc-1", concept_id: "K_INT", duration: 14, difficulty: 2, rating: 4.5, tags: ["foundations"] },
  { id: "R012", type: "video", url: "https://www.khanacademy.org/math/calculus-2/sequences-series-topic", concept_id: "K_SER", duration: 16, difficulty: 3, rating: 4.4, tags: ["deep-dive"] },
  { id: "R013", type: "notes", url: "https://tutorial.math.lamar.edu/Classes/DE/DE.aspx", concept_id: "K_DIFF", duration: 20, difficulty: 4, rating: 4.2, tags: ["reference","deep-dive"] },
  { id: "R006", type: "quiz", url: "https://www.sparknotes.com/physics/kinematics/", concept_id: "K_KIN", duration: 10, difficulty: 2, rating: 4.0, tags: ["practice"] },
  { id: "R014", type: "video", url: "https://www.khanacademy.org/science/physics/magnetic-forces-and-magnetic-fields", concept_id: "K_EM", duration: 13, difficulty: 3, rating: 4.5, tags: ["visual"] },
  { id: "R019", type: "video", url: "https://www.khanacademy.org/science/physics/special-relativity", concept_id: "K_REL", duration: 11, difficulty: 3, rating: 4.6, tags: ["conceptual"] },
  { id: "R020", type: "video", url: "https://www.khanacademy.org/science/physics/quantum-physics", concept_id: "K_QM", duration: 15, difficulty: 4, rating: 4.7, tags: ["deep-dive"] },
  { id: "R007", type: "video", url: "https://www.khanacademy.org/science/biology/structure-of-a-cell", concept_id: "K_BIO", duration: 11, difficulty: 1, rating: 4.5, tags: ["foundations","visual"] },
  { id: "R015", type: "quiz", url: "https://www.biologycorner.com/worksheets/genetics.html", concept_id: "K_GEN", duration: 9, difficulty: 2, rating: 4.2, tags: ["practice"] },
  { id: "R016", type: "video", url: "https://www.khanacademy.org/science/ap-biology/dna-technology", concept_id: "K_DNA", duration: 12, difficulty: 3, rating: 4.4, tags: ["visual"] },
  { id: "R021", type: "video", url: "https://www.khanacademy.org/science/biology/central-dogma-topic", concept_id: "K_PROT", duration: 13, difficulty: 3, rating: 4.5, tags: ["visual","deep-dive"] },
  { id: "R008", type: "video", url: "https://www.khanacademy.org/science/chemistry/stoichiometry-mp", concept_id: "K_CHE", duration: 13, difficulty: 2, rating: 4.6, tags: ["foundations"] },
  { id: "R017", type: "video", url: "https://www.khanacademy.org/science/organic-chemistry/organic-structures", concept_id: "K_ORG", duration: 14, difficulty: 3, rating: 4.3, tags: ["conceptual"] },
  { id: "R022", type: "notes", url: "https://chem.libretexts.org/Bookshelves/Physical_and_Theoretical_Chemistry", concept_id: "K_THERM", duration: 18, difficulty: 4, rating: 4.1, tags: ["reference"] },
  { id: "R009", type: "video", url: "https://www.khanacademy.org/computing/computer-programming/intro-to-js/loops", concept_id: "K_CS1", duration: 9, difficulty: 1, rating: 4.7, tags: ["foundations","visual"] },
  { id: "R010", type: "quiz", url: "https://www.hackerrank.com/domains/tutorials/10-days-of-javascript", concept_id: "K_CS1", duration: 10, difficulty: 2, rating: 4.5, tags: ["practice"] },
  { id: "R011", type: "notes", url: "https://visualgo.net/en/list", concept_id: "K_CS2", duration: 8, difficulty: 2, rating: 4.6, tags: ["visual","reference"] },
  { id: "R018", type: "video", url: "https://www.khanacademy.org/computing/computer-science/algorithms/recursive-algorithms", concept_id: "K_CS4", duration: 10, difficulty: 3, rating: 4.5, tags: ["conceptual"] },
  { id: "R023", type: "notes", url: "https://cp-algorithms.com/", concept_id: "K_ALG", duration: 17, difficulty: 4, rating: 4.8, tags: ["reference","deep-dive"] },
  { id: "R024", type: "video", url: "https://www.youtube.com/watch?v=rlKcLwIeUo8", concept_id: "K_ARCH", duration: 12, difficulty: 3, rating: 4.2, tags: ["visual"] },
  { id: "R025", type: "notes", url: "https://www.databasestar.com/database-normalization/", concept_id: "K_DB", duration: 9, difficulty: 2, rating: 4.4, tags: ["foundations","reference"] },
  { id: "R026", type: "video", url: "https://www.khanacademy.org/math/statistics-probability/random-variables-stats-library", concept_id: "K_STATS", duration: 14, difficulty: 2, rating: 4.6, tags: ["foundations"] },
  { id: "R027", type: "video", url: "https://www.khanacademy.org/math/linear-algebra/matrix-transformations", concept_id: "K_LINALG", duration: 13, difficulty: 2, rating: 4.7, tags: ["visual"] },
  { id: "R028", type: "video", url: "https://www.khanacademy.org/science/ap-biology/gene-expression-and-regulation/dna-and-rna-technology/v/blast-database-search", concept_id: "K_BIOINF", duration: 11, difficulty: 4, rating: 4.5, tags: ["deep-dive"] },
];

export const dayOrder = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
